export const appConfig = {
  jwtSecret: process.env.JWT_SECRET ?? 'dev-secret',
  jwtExpiry: process.env.JWT_EXPIRY ?? '1h',
  refreshTokenTtlDays: Number(process.env.REFRESH_TOKEN_TTL_DAYS ?? '30'),
  refreshCookieName: process.env.REFRESH_COOKIE_NAME ?? 'pft_refresh_token',
  refreshCookieSecure: process.env.REFRESH_COOKIE_SECURE === 'true',
  refreshCookieSameSite: (process.env.REFRESH_COOKIE_SAME_SITE ?? 'lax') as 'lax' | 'strict' | 'none',
  googleClientId: process.env.GOOGLE_CLIENT_ID ?? '',
  googleClientSecret: process.env.GOOGLE_CLIENT_SECRET ?? '',
  googleRedirectUri: process.env.GOOGLE_REDIRECT_URI ?? '',
  authSuccessRedirect: process.env.AUTH_SUCCESS_REDIRECT ?? 'http://localhost:5173/auth/callback',
  importGmailUser: process.env.IMPORT_GMAIL_USER ?? 'me',
  importGoogleRedirectUri:
    process.env.IMPORT_GOOGLE_REDIRECT_URI ?? process.env.GOOGLE_REDIRECT_URI ?? '',
  importGmailScope:
    process.env.IMPORT_GMAIL_SCOPE ?? 'https://www.googleapis.com/auth/gmail.readonly',
  importReauthSuccessRedirect: process.env.IMPORT_REAUTH_SUCCESS_REDIRECT ?? 'http://localhost:5173/settings',
  importReauthErrorRedirect: process.env.IMPORT_REAUTH_ERROR_REDIRECT ?? 'http://localhost:5173/settings',
  importGmailMaxResults: Number(process.env.IMPORT_GMAIL_MAX_RESULTS ?? '500'),
  importLabelSbi: process.env.IMPORT_LABEL_SBI ?? 'CC Transactions/SBI',
  importLabelHdfc: process.env.IMPORT_LABEL_HDFC ?? 'CC Transactions/HDFC',
  importLabelIcici: process.env.IMPORT_LABEL_ICICI ?? 'CC Transactions/ICICI',
  statementLabelSbi: process.env.STATEMENT_LABEL_SBI ?? 'CC Statements/sbi_xx5965_statements',
  statementLabelHdfc: process.env.STATEMENT_LABEL_HDFC ?? 'CC Statements/hdfc_xx9335_statements',
  statementLabelIcici5000:
    process.env.STATEMENT_LABEL_ICICI_5000 ?? 'CC Statements/icici_xx5000_statements',
  statementLabelIcici9003:
    process.env.STATEMENT_LABEL_ICICI_9003 ?? 'CC Statements/icici_xx9003_statements',
  statementLabelCsb: process.env.STATEMENT_LABEL_CSB ?? 'CC Statements/csb_xx4345_statements',
  statementLabelSlice: process.env.STATEMENT_LABEL_SLICE ?? 'CC Statements/slice_xx6447_statements',
  // Legacy flow passed null password by default for non-CSB labels.
  statementPdfPasswordSbi: process.env.STATEMENT_PDF_PASSWORD_SBI ?? '',
  statementPdfPasswordHdfc: process.env.STATEMENT_PDF_PASSWORD_HDFC ?? 'SUMA0709',
  statementPdfPasswordIcici5000: process.env.STATEMENT_PDF_PASSWORD_ICICI_5000 ?? '',
  statementPdfPasswordIcici9003: process.env.STATEMENT_PDF_PASSWORD_ICICI_9003 ?? '',
  // Legacy CSB flow derived candidates from label/card suffix; keep a deterministic first fallback.
  statementPdfPasswordCsb: process.env.STATEMENT_PDF_PASSWORD_CSB ?? 'SUMA0709',
  statementDefaultPdfPassword: process.env.STATEMENT_DEFAULT_PDF_PASSWORD ?? '',
  statementGeminiApiKey: process.env.STATEMENT_GEMINI_API_KEY ?? '',
  statementGeminiModel: process.env.STATEMENT_GEMINI_MODEL ?? 'gemini-2.5-flash',
  statementGeminiMaxAttempts: Number(process.env.STATEMENT_GEMINI_MAX_ATTEMPTS ?? '4'),
  statementGeminiBackoffMs: Number(process.env.STATEMENT_GEMINI_BASE_BACKOFF_MS ?? '2000'),
  statementSyncVerboseLogs: process.env.STATEMENT_SYNC_VERBOSE_LOGS !== 'false',
  statementSyncVerboseCardKey: process.env.STATEMENT_SYNC_VERBOSE_CARD_KEY ?? 'ICICI_XX5000',
  importDebugParserInput: process.env.IMPORT_DEBUG_PARSER_INPUT === 'true',
  importDebugBodyMaxLen: Number(process.env.IMPORT_DEBUG_BODY_MAX_LEN ?? '1200'),
}
